MindmApp/urls.py
from django.urls import path
from . import views

app_name = "MindmApp"

urlpatterns = [
    path("", views.index, name="index"),
    # view to login
    path("login", views.login_view, name="login"),
    # view to logout
    path("logout", views.logout_view, name="logout"),
    # view to register
    path("register", views.register_view, name="register"),
    # main app url
    path("main", views.main_view, name="main"),
    # url to send textarea changes to server
    path("getText", views.getText, name="getText"),
    # url to get text from database to show in main.html
    path("getTextToShow", views.getTextToShow, name="getTextToShow"),
    # url to send chosen node image to server
    path("chooseImage", views.chooseImage, name="chooseImage"),
    # url to get node image name from database to show in main.html
    path("loadImages", views.loadImages, name="loadImages"),
    #change mindmap name
    path("mindmap_Name", views.mindmap_Name, name="mindmap_Name"),
    #get mindmap Name
    path("get_mindmap_name", views.get_mindmap_name, name="get_mindmap_name")
]

capstone/urls.py
from django.contrib import admin
from django.urls import path, include
#import settings for media storage
from django.conf import settings
#import the place where media is stored
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("MindmApp.urls"))
]

MindmApp/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

#If error django: no such table pops up, you must sync the database when you migrate:
#               python manage.py migrate --run-syncdb

# Implementation of case case_insensitive username login capability
class CustomUserManager(UserManager):
    def get_by_natural_key(self, username):
        case_insensitive_username_field = '{}__iexact'.format(self.model.USERNAME_FIELD)
        return self.get(**{case_insensitive_username_field: username})

# user table
class CustomUser(AbstractUser):
    # allow for Implementation of CustomUserManager class
    objects = CustomUserManager()

# user text areas table
class UserTextArea(models.Model):
    user = models.ForeignKey("CustomUser", on_delete=models.CASCADE, related_name="userOfText")
    textAreaId = models.TextField(blank=False)
    textAreaPlaceholder = models.TextField(blank=True)

# node images chosen by user table
class UserImages(models.Model):
    user = models.ForeignKey("CustomUser", on_delete=models.CASCADE, related_name="userOfImage")
    thisLinkText = models.TextField(blank=True)
    imageDropdownId = models.TextField(blank=False)

class MindMapName(models.Model):
    user = models.ForeignKey("CustomUser", on_delete=models.CASCADE, related_name="userOfMindMapName")
    name = models.TextField(blank=True)

MindmApp/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
import json
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.db import IntegrityError, InternalError
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
import os
from django.conf import settings
from django.views.decorators.csrf import csrf_protect


#login and register view
@csrf_exempt
def index(request):
    return render(request, "MindmApp/index.html", {
        "welcome": "Welcome",
    })

#login view
@ensure_csrf_cookie
def login_view(request):
    if request.method == "POST":

        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            return HttpResponseRedirect(reverse("MindmApp:main"))
        else:
            return render(request, "MindmApp/index.html", {
                "warning": "Incorrect login details, please try again."
            })
    else:
        return render(request, "MindmApp/index.html", {
            "warning": "You are not authorized. Please try again."
        })

#logout view
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("MindmApp:index"))

#register view
@ensure_csrf_cookie
def register_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # do passwords match?
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "MindmApp/index.html", {
                "warning": "Passwords must match."
            })

        # create new user, or else it is already a taken username.
        try:
            user = CustomUser.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "MindmApp/index.html", {
                "warning": "Username already taken."
            })

        # login using CSRF cookie
        login(request, user)

        #list of all unchangeable textarea id's
        allTextareas = ["Tp2_n11", "Tp7_n10", "Tp1_n10", "Tp2_n12", "Tp4_n10", "Tp5_n10", "Tp2_n10", "Tp1_n", "Tp2_n8", "Tp2_n6", "Tp1_n6", "Tp1_n8", "Tp5_center", "Tp4_center", "Tp3_n8", "Tp4_n8", "Tp6_n8", "Tp8_n8", "Tp12_n4", "Tp7_n6", "Tp11_n4", "Tp8_n10", "Tp9_n3", "Tp10_n3", "Tp1_center", "Tp2_center", "Tp8_n3", "Tp3_center", "Tp6_n2", "Tp7_n2", "Tp6_center", "Tp6_n7", "Tp8_n7", "Tp9_n2", "Tp2_n7", "Tp1_n7", "Tp9_n7", "Tp5_n9", "Tp6_n9", "Tp7_n9", "Tp8_n9", "Tp9_n9", "Tp1_n9", "Tp2_n9", "Tp3_n9", "Tp4_n5", "Tp5_n5", "Tp1_n5", "Tp1_nFirst", "Tp7_nFirst", "Tp8_nFirst", "Tp1_n2", "Tp2_n2", "Tp3_n2", "Tp3_n5", "Tp8_n2", "Tp3_n7", "Tp1_n3", "Tp2_n3", "Tp3_n3", "Tp5_n2", "Tp7_n4", "Tp6_n4", "Tp5_n4", "Tp4_n4", "Tp3_n4", "Tp4_n3", "Tp5_n3", "Tp6_n3", "Tp7_n3", "Tp5_n6", "Tp6_n6"]

        #list of all unchangeable node id's
        neurons = ["nCenter_dropdown", "nFirst_dropdown", "n2_dropdown", "n3_dropdown", "n4_dropdown", "n5_dropdown", "n6_dropdown", "n7_dropdown", "n8_dropdown", "n9_dropdown", "n10_dropdown", "n11_dropdown", "n12_dropdown"]

        # create database objects for all nodes.
        for i in neurons:
            UserImages.objects.create(user=user, imageDropdownId=i)

        # create database objects for all textareas.
        for i in allTextareas:
            UserTextArea.objects.create(user=user, textAreaId=i)

        MindMapName.objects.create(user=user)


        return render(request, "MindmApp/index.html", {
            "message": "Registration successful! Please login."
        })
    else:
        return render(request, "MindmApp/index.html")


# login using CSRF cookie
@login_required
def main_view(request):
    user = request.user

    # get static subfolders
    STATIC_SUBFOLDER = os.path.join(settings.BASE_DIR, "staticfiles/MindmApp//media")
    #get list of images from django media folder (declared in settings.py)

    image_list =[]
    for root, dirs, files in os.walk(STATIC_SUBFOLDER):
        for file in files:
            image_list.append(file.split('.')[0])


    image_list = list(set(image_list))
    # remove image extension from text to view in dropdown menu
    # image_list = [os.path.splitext(x)[0] for x in lst]

    #return list of images to show in dropdown menu's in main app (main.html)
    return render(request, "MindmApp/main.html", {
            "imageList": image_list,
        })


@login_required
@csrf_exempt #csrf only needed for logins
def getText(request): #update database with custom user text for text area
    #if fetch request was POST
    if request.method == "POST":

        #get the json data from fetch request
        data = json.loads(request.body)
        user = request.user
        textAreaId = data.get("textAreaId")
        textAreaPlaceholder = data.get("textAreaPlaceholder")

        # update database for user text in textarea
        userTextArea = UserTextArea.objects.get(user=user, textAreaId=textAreaId)
        print(userTextArea.user)
        print(userTextArea.textAreaId)
        userTextArea.textAreaPlaceholder = textAreaPlaceholder
        userTextArea.save()

        # return a Json response with the name of the user who updated the textarea, and the id of the text area.
        return JsonResponse({"message": f"user: {user}\ntextAreaId: {textAreaId}"}, status=500)

#need to be logged in to get textarea information
@login_required
@csrf_exempt
def getTextToShow(request):
    if request.method == "PUT":
        # get the currect user
        user = request.user
        data = json.loads(request.body)
        textAreaId = data.get("textAreaId")

        try: #get the text for a textarea for the correct user
            userTextArea = UserTextArea.objects.get(user=user, textAreaId=textAreaId)
            textAreaPlaceholder = userTextArea.textAreaPlaceholder
            return JsonResponse({"textAreaPlaceholder": f"{textAreaPlaceholder}"}, status=201)

        # handle exceptions with Json responses
        except ObjectDoesNotExist:
            return JsonResponse({"problem": f"There is no text for this..."}, status=500)
        except MultipleObjectsReturned:
            return JsonResponse({"problem": f"Too many objects returned..."}, status=500)
        except InternalError:
            return JsonResponse({"problem": f"problem"}, status=500)

    else:
        return JsonResponse({"problem": f"Not a proper request"}, status=500)


@login_required
@csrf_exempt
def chooseImage(request):
    if request.method == "PUT":
        # get the current user
        user = request.user

        # get user data from fetch PUT request
        data = json.loads(request.body)

        # get text for specific textarea (based on id) typed in by user
        thisLinkText = data.get("thisLinkText")
        imageDropdownId = data.get("imageDropdownId")

        # update image chosen for node from dropdown in main.html
        userImages = UserImages.objects.get(user=user, imageDropdownId=imageDropdownId)
        userImages.thisLinkText = thisLinkText
        userImages.save()

        # respond with Json response containing the user text
        return JsonResponse({"thisLinkText": f"{thisLinkText}"}, status=201)


@login_required
@csrf_exempt
def loadImages(request):
    # get the current user
    user = request.user

    # reason for all of the following:
            # get text for each text area in the app for the specified user (line 192)

    nCenter_dropdown = "nCenter_dropdown"
    nCenter_dropdown = UserImages.objects.get(user=user, imageDropdownId=nCenter_dropdown)
    nCenter_dropdown = nCenter_dropdown.thisLinkText

    nFirst_dropdown = "nFirst_dropdown"
    nFirst_dropdown = UserImages.objects.get(user=user, imageDropdownId=nFirst_dropdown)
    nFirst_dropdown = nFirst_dropdown.thisLinkText

    n2_dropdown = "n2_dropdown"
    n2_dropdown = UserImages.objects.get(user=user, imageDropdownId=n2_dropdown)
    n2_dropdown = n2_dropdown.thisLinkText

    n3_dropdown = "n3_dropdown"
    n3_dropdown = UserImages.objects.get(user=user, imageDropdownId=n3_dropdown)
    n3_dropdown = n3_dropdown.thisLinkText

    n4_dropdown = "n4_dropdown"
    n4_dropdown = UserImages.objects.get(user=user, imageDropdownId=n4_dropdown)
    n4_dropdown = n4_dropdown.thisLinkText

    n5_dropdown = "n5_dropdown"
    n5_dropdown = UserImages.objects.get(user=user, imageDropdownId=n5_dropdown)
    n5_dropdown = n5_dropdown.thisLinkText

    n6_dropdown = "n6_dropdown"
    n6_dropdown = UserImages.objects.get(user=user, imageDropdownId=n6_dropdown)
    n6_dropdown = n6_dropdown.thisLinkText

    n7_dropdown = "n7_dropdown"
    n7_dropdown = UserImages.objects.get(user=user, imageDropdownId=n7_dropdown)
    n7_dropdown = n7_dropdown.thisLinkText

    n8_dropdown = "n8_dropdown"
    n8_dropdown = UserImages.objects.get(user=user, imageDropdownId=n8_dropdown)
    n8_dropdown = n8_dropdown.thisLinkText

    n9_dropdown = "n9_dropdown"
    n9_dropdown = UserImages.objects.get(user=user, imageDropdownId=n9_dropdown)
    n9_dropdown = n9_dropdown.thisLinkText

    n10_dropdown = "n10_dropdown"
    n10_dropdown = UserImages.objects.get(user=user, imageDropdownId=n10_dropdown)
    n10_dropdown = n10_dropdown.thisLinkText

    n11_dropdown = "n11_dropdown"
    n11_dropdown = UserImages.objects.get(user=user, imageDropdownId=n11_dropdown)
    n11_dropdown = n11_dropdown.thisLinkText

    n12_dropdown = "n12_dropdown"

MindmApp/templates/MindmApp/index.html
{% extends "MindmApp/layout.html" %}
{% load static %}
{% block body %}


  <!--/////////// CSS for registration/login page ////////////-->
  <link rel="stylesheet" href="{% static 'MindmApp/index.css' %}">


<!-- below are warnings or messages that are only visible if triggered -->
  <p id="paragraph" style="text-align: center;">{{warning}}</p>
  <p id="messageId" style="text-align: center;">{{message}}</p>

  <div id="app">
  </div>


<!-- below is react for login/register page -->
  <script>

//in react, every html element must have a closing tag, e.g. not <input> but <input />
        //////////////////////////////////////////////////////////
        //////////////////////App Component///////////////////////
        //////////////////////////////////////////////////////////



        "use strict";

      function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

      class App extends React.Component {
        constructor(...args) {
          super(...args);

          _defineProperty(this, "state", {
            whatState: '',
            showLogin: true,
            showRegister: true,
            registerMargin: true
          });
        }

        //////////////////////////////////////////////////////////
        /////////// render() function of App Component////////////
        render() {
          ////////////change margin of register button //////////////
          if (this.state.showLogin == false && this.state.showRegister == true) {
            if (document.getElementById("hideRegister")) {
              document.getElementById("hideRegister").style.margin = "0px 0px 0px 0px";
            }
          }

          var showLogin = this.state.showLogin;
          var showRegister = this.state.showRegister; //////////If statement to show/hide buttons/////////////

          // When the user clicks login to go to the login form
          if (showLogin) {
            var buttonLogin = /*#__PURE__*/React.createElement("button", {
              class: "btn btn-primary purpleLogins",
              onClick: e => this.setState({
                whatState: e.target.name,
                showLogin: false,
                showRegister: true,
                registerMargin: false
              }),
              name: "login",
              id: "hideLogin"
            }, "Login");
          } else {}

          // When the user clicks register to go to the register form
          if (showRegister) {
            var buttonRegister = /*#__PURE__*/React.createElement("button", {
              class: "btn btn-primary purpleLogins",
              onClick: e => this.setState({
                whatState: e.target.name,
                showRegister: false,
                showLogin: true
              }),
              name: "register",
              id: "hideRegister"
            }, "Register");
          } //////////////////////////////////////////////////////////
          //////////////////////APP RETURN /////////////////////////


          return /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
            id: "buttonDiv"
          }, buttonLogin, buttonRegister, this.state.problem, this.handleLog(this.state.whatState)));
        } //////////////////////////////////////////////////////////
        /////////////////APP FUNCTION handleLog///////////////////


        handleLog(whatState) {
          if (whatState == "login") return /*#__PURE__*/React.createElement(LoginView, null);
          if (whatState == "register") return /*#__PURE__*/React.createElement(RegView, null);
        }

      } //////////////////////////////////////////////////////////
      ////////////////////RegView Component/////////////////////
      //////////////////////////////////////////////////////////

      class RegView extends React.Component {
        constructor(...args) {
          super(...args);

          _defineProperty(this, "state", {
            registered: false,
            bePatient: ""
          });
        }

        render() {

          // get Cross-Site Request Forgery token
          var csrftokenregister = "{{ csrf_token }}";
          // create react element to pass into form as csrf csrfToken
          // var instead of const is used instead, in order to reload CSRF token on page refresh
          var csrfTokenRegister = React.createElement("input", {
            type: "hidden",
            name: "csrfmiddlewaretoken",
            value: csrftokenregister
          })

          var registerButton = /*#__PURE__*/React.createElement("input", {
            class: "btn btn-outline-success purpleLogin",
            type: "submit",
            value: "Register",
            onClick: e => this.setState({
              registered: true,
              bePatient: alert("Please be patient, this might take a couple seconds...")
            })
          });


          return (
            /*#__PURE__*/
            //↓↓↓↓↓↓↓↓ HTML code for Register Form ↓↓↓↓↓↓↓↓\\
            React.createElement("div", {
              id: "registerFormDiv"
            }, this.state.bePatient, /*#__PURE__*/React.createElement("br", null), /*#__PURE__*/React.createElement("form", {
              id: "registerForm",
              method: "post",
              action: "{% url 'MindmApp:register' %}"
            },csrfTokenRegister, /*#__PURE__*/React.createElement("div", {
              class: "form-group"
            }, /*#__PURE__*/React.createElement("input", {
              class: "form-control loginPasswordInput",
              autofocus: true,
              type: "text",
              name: "username",
              placeholder: "Username",
              id: "registerUsernameInput"
            })), /*#__PURE__*/React.createElement("div", {
              class: "form-group"
            }, /*#__PURE__*/React.createElement("input", {
              class: "form-control loginPasswordInput",
              type: "email",
              name: "email",
              placeholder: "Email Address",
              id: "registerEmailInput"
            })), /*#__PURE__*/React.createElement("div", {
              class: "form-group"
            }, /*#__PURE__*/React.createElement("input", {
              class: "form-control loginPasswordInput",
              type: "password",
              name: "password",
              placeholder: "Password",
              id: "registerPasswordInput"
            })), /*#__PURE__*/React.createElement("div", {
              class: "form-group"
            }, /*#__PURE__*/React.createElement("input", {
              class: "form-control loginPasswordInput",
              type: "password",
              name: "confirmation",
              placeholder: "Confirm Password",
              id: "registerConfirmationInput"
            })), registerButton))
          );
        }

      } //////////////////////////////////////////////////////////
      ////////////////////LoginView Component///////////////////
      //////////////////////////////////////////////////////////


      class LoginView extends React.Component {
        constructor(...args) {
          super(...args);

          _defineProperty(this, "state", {
            loggedIn: false
          });
        }

        render() {

          // csrf token for security reasons
          var csrftoken = "{{ csrf_token }}";
          var csrfToken = React.createElement("input", {
            type: "hidden",
            name: "csrfmiddlewaretoken",
            value: csrftoken
          })

          // functionality of login button
          var logginButton = /*#__PURE__*/React.createElement("input", {
            class: "btn btn-outline-success purpleLogin",
            type: "submit",
            value: "Login",
            onClick: e => this.setState({
              loggedIn: true
            })
          });


          // render html for login form
          return /*#__PURE__*/React.createElement("div", {
            id: "loginFormDiv"
          }, /*#__PURE__*/React.createElement("form", {
            id: "loginForm",
            method: "post",
            id: "formMarginTop",
            action: "{% url 'MindmApp:login' %}"
          },csrfToken, /*#__PURE__*/React.createElement("p", {
            id: "showError"
          }), /*#__PURE__*/React.createElement("div", {
            class: "form-group"
          }, /*#__PURE__*/React.createElement("input", {
            autofocus: true,
            class: "form-control loginPasswordInput",
            type: "text",
            name: "username",
            placeholder: "Username",
            id: "loginUsernameInput"
          })), /*#__PURE__*/React.createElement("div", {
            class: "form-group"
          }, /*#__PURE__*/React.createElement("input", {
            class: "form-control loginPasswordInput",
            type: "password",
            name: "password",
            placeholder: "Password",
            id: "loginPasswordInput"
          })), logginButton));
        }

      } //////////////////////////////////////////////////////////
      ////////////// USED TO RENDER ENTIRE PAGE ////////////////


      ReactDOM.render( /*#__PURE__*/React.createElement(App, null), document.querySelector("#app"));

  </script>

<!-- copyright -->
<p style="position: fixed; color: white; bottom: 0; right: 0; margin-right: 2px; font-size: 12px; margin-bottom: 0px;" id="copyright">© Jonathon Durno 2021</p>

{% endblock %}

MindmApp/templates/MindmApp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-http-equiv="X-UA-Compatible" content="ie-edge" />

    <title>MindmApp</title>

    <link rel="shortcut icon" type="image/icon" href="{% static 'MindmApp/favicon.ico' %}"/>

    <!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ Bootstrap source code ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ React source code ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->
    <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>


      <script>

      </script>

  </head>
  <body>

    {% block body %}
    {% endblock %}
  </body>
</html>